version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    networks:
      - linkToDb
    depends_on:
      - "dbMySql"
  dbMySql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CharliePrm88
      MYSQL_DATABASE: psigest
    networks:
      - linkToDb

networks:
  linkToDb:
